/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/vendor_machine/scene.gltf -t -r public
Author: @sanyabeast (https://sketchfab.com/sanchibbo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eelislays-retro-coca-cola-fridge-03d5d9552c884d1795cc810f835bd2fe
Title: Eelislay`s Retro Coca Cola Fridge
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    ['main_steel.001']: THREE.MeshStandardMaterial
    ['alt_steel.001']: THREE.MeshStandardMaterial
  }
}

export default function Vendor(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/vendor_machine/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={6} castShadow receiveShadow>
        <mesh geometry={nodes.Object_6.geometry} material={materials['main_steel.001']} castShadow receiveShadow/>
        <mesh geometry={nodes.Object_8.geometry} material={materials['alt_steel.001']} castShadow receiveShadow/>
      </group>
    </group>
  )
}

useGLTF.preload('/models/vendor_machine/scene.gltf')
