/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/chair/scene.gltf -t -r public
Author: Brendan (https://sketchfab.com/Brendan52)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/big-leather-chair-7c8b8b8c7e4c494fa908eac4ae725092
Title: Big Leather Chair
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Armrests_low_M_PROPS2_0: THREE.Mesh
    Cushion_low_M_PROPS2_0: THREE.Mesh
    Back_low_M_PROPS2_0: THREE.Mesh
    Leg1_low_M_PROPS2_0: THREE.Mesh
    Leg2_low_M_PROPS2_0: THREE.Mesh
    Leg3_low_M_PROPS2_0: THREE.Mesh
    Leg4_low_M_PROPS2_0: THREE.Mesh
  }
  materials: {
    M_PROPS2: THREE.MeshStandardMaterial
  }
}

export default function Chair(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chair/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.015} castShadow receiveShadow>
        <group position={[230.41, 0, 64.87]} castShadow receiveShadow>
          <mesh geometry={nodes.Armrests_low_M_PROPS2_0.geometry} material={materials.M_PROPS2} castShadow receiveShadow/>
          <mesh geometry={nodes.Cushion_low_M_PROPS2_0.geometry} material={materials.M_PROPS2} castShadow receiveShadow/>
          <mesh geometry={nodes.Back_low_M_PROPS2_0.geometry} material={materials.M_PROPS2} castShadow receiveShadow/>
          <mesh geometry={nodes.Leg1_low_M_PROPS2_0.geometry} material={materials.M_PROPS2} castShadow receiveShadow/>
          <mesh geometry={nodes.Leg2_low_M_PROPS2_0.geometry} material={materials.M_PROPS2} castShadow receiveShadow/>
          <mesh geometry={nodes.Leg3_low_M_PROPS2_0.geometry} material={materials.M_PROPS2} castShadow receiveShadow/>
          <mesh geometry={nodes.Leg4_low_M_PROPS2_0.geometry} material={materials.M_PROPS2} castShadow receiveShadow/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chair/scene.gltf')
