/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/garage/scene.gltf -t -r public
Author: Connections XR (https://sketchfab.com/connectionsxr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/garage-de7a8dd4309e461cbc99be85f928b480
Title: Garage
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { Plane, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import TireRack from './TireRack'

type GLTFResult = GLTF & {
  nodes: {
    Floor_Cement_M_Floor_0: THREE.Mesh
    Walls_M_Wall_0: THREE.Mesh
    Door_Trim_M_WoodTrim_0: THREE.Mesh
    Door_M_DoorPanel_0: THREE.Mesh
    Door_WindowFrame_M_WindowFrame_0: THREE.Mesh
    Locker_Shelf_M_Locker_0: THREE.Mesh
    Locker_Door_Panel_Left_M_LockerDoor_0: THREE.Mesh
    Locker_Door_Handle_Left_M_SteelBrushed_0: THREE.Mesh
    Poster_CowGirl1_M_PosterCowGirl_0: THREE.Mesh
    Poster_Track1_M_PosterTrack_0: THREE.Mesh
    Locker_Door_Panel_Right_M_LockerDoor_0: THREE.Mesh
    Locker_Door_Handle_Right_M_SteelBrushed_0: THREE.Mesh
    Poster_CowGirl_M_PosterCowGirl_0: THREE.Mesh
    Poster_MineWeld_M_PosterMineWeld_0: THREE.Mesh
    Poster_Warning_M_PosterWarning_0: THREE.Mesh
    Poster_Track_M_PosterTrack_0: THREE.Mesh
    Poster_NoSmoking_M_PosterNoSmoking_0: THREE.Mesh
  }
  materials: {
    M_Floor: THREE.MeshStandardMaterial
    M_Wall: THREE.MeshStandardMaterial
    M_WoodTrim: THREE.MeshStandardMaterial
    M_DoorPanel: THREE.MeshStandardMaterial
    M_WindowFrame: THREE.MeshStandardMaterial
    M_PosterCowGirl: THREE.MeshStandardMaterial
    M_PosterTrack: THREE.MeshStandardMaterial
    M_PosterMineWeld: THREE.MeshStandardMaterial
    M_PosterWarning: THREE.MeshStandardMaterial
    M_PosterNoSmoking: THREE.MeshStandardMaterial
  }
}

export function Garage(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/garage/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} castShadow receiveShadow>
      <mesh position={[0, 5, -25]} receiveShadow>
            <boxGeometry args={[20, 10, 1]}/>
            <meshStandardMaterial color={'yellow'}/>
          </mesh>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004} position={[0,0,0]} castShadow receiveShadow>
        <group rotation={[Math.PI / 2, 0, 0]} castShadow receiveShadow>
          <TireRack />
          <mesh geometry={nodes.Floor_Cement_M_Floor_0.geometry} material={materials.M_Floor} castShadow receiveShadow/>
          {/* <mesh geometry={nodes.Walls_M_Wall_0.geometry} material={materials.M_Wall} castShadow receiveShadow/> */}
          <mesh geometry={nodes.Door_Trim_M_WoodTrim_0.geometry} material={materials.M_WoodTrim} castShadow receiveShadow/>
          <mesh geometry={nodes.Door_M_DoorPanel_0.geometry} material={materials.M_DoorPanel} castShadow receiveShadow/>
          <mesh geometry={nodes.Door_WindowFrame_M_WindowFrame_0.geometry} material={materials.M_WindowFrame} castShadow receiveShadow/>

          
          
          <mesh geometry={nodes.Poster_CowGirl_M_PosterCowGirl_0.geometry} material={materials.M_PosterCowGirl} position={[1678.75, 1823.83, 2803.91]} rotation={[0, 0, Math.PI / 2]} scale={[2.35, 1.6, 1.6]} castShadow receiveShadow/>
          <mesh geometry={nodes.Poster_MineWeld_M_PosterMineWeld_0.geometry} material={materials.M_PosterMineWeld} position={[1678.75, 1731.51, 2380.12]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[2.22, 1.18, 1.1]} castShadow receiveShadow/>
          <mesh geometry={nodes.Poster_Warning_M_PosterWarning_0.geometry} material={materials.M_PosterWarning} position={[1672.09, 2228.1, 1726.66]} rotation={[0, 0, Math.PI / 2]} scale={[4.68, 3.18, 3.18]} castShadow receiveShadow/>
          <mesh geometry={nodes.Poster_Track_M_PosterTrack_0.geometry} material={materials.M_PosterTrack} position={[1678.75, 1410.26, 2419.28]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1.75, 1.19, 1.19]} castShadow receiveShadow/>
          <mesh geometry={nodes.Poster_NoSmoking_M_PosterNoSmoking_0.geometry} material={materials.M_PosterNoSmoking} position={[-2437.6, 2293.47, -5968.85]} rotation={[Math.PI / 2, 0, 0]} scale={[2.92, 1.99, 2.15]} castShadow receiveShadow/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/garage/scene.gltf')
