/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/garage2/scene.gltf -t -r public
Author: whoyee (https://sketchfab.com/whoyee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gallery-space-8dc19249963d4d2e9e93f48dd3c31f7c
Title: Gallery Space
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Material-material']: THREE.Mesh
    ['Spot_Lights-material']: THREE.Mesh
  }
  materials: {
    material_0: THREE.LineBasicMaterial
    Material: THREE.MeshBasicMaterial
    Spot_Lights: THREE.MeshBasicMaterial
  }
}

export default function Room(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/garage2/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} position={[0,0,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3}>
        {/* <lineSegments geometry={nodes.Object_3.geometry} material={materials.material_0} /> */}
        <mesh geometry={nodes['Material-material'].geometry} material={materials.Material} />
        <mesh geometry={nodes['Spot_Lights-material'].geometry} material={materials.Spot_Lights} position={[0.05, -6.54, 3.4]} scale={0.1} />
      </group>
    </group>
  )
}

useGLTF.preload('/garage2/scene.gltf')
