/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/tire_rack/scene.gltf -t -r public
Author: 3ddominator (https://sketchfab.com/roughdominator)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tire-rack-3e4fdc69fe5f428082242a32a343c28a
Title: Tire Rack
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['TireRack_low_Material_#0_0']: THREE.Mesh
  }
  materials: {
    Material_0: THREE.MeshStandardMaterial
  }
}

export default function TireRack(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/tire_rack/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} position={[0,0,0]} castShadow receiveShadow>
      <group scale={0.013} castShadow receiveShadow>
        <group rotation={[-Math.PI / 2, 0, 0]} castShadow receiveShadow>
          <mesh geometry={nodes['TireRack_low_Material_#0_0'].geometry} material={materials.Material_0} position={[0, 0, 44.16]} castShadow receiveShadow/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tire_rack/scene.gltf')
