/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/tire/scene.gltf -t -r public
Author: kalvsxjiro (https://sketchfab.com/kalvsxjiro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tire-tread-925e6fa4b9ae449aa4bec16c6a67944d
Title: Tire tread
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    polySurface9_RUBBER_TIRE_0: THREE.Mesh
    polySurface9_RUBBER_TIRE_0_1: THREE.Mesh
    polySurface9_RUBBER_DUST_0: THREE.Mesh
  }
  materials: {
    RUBBER_TIRE: THREE.MeshStandardMaterial
    RUBBER_DUST: THREE.MeshStandardMaterial
  }
}

const rubber = new THREE.MeshPhysicalMaterial({ color: 'black', roughness: 1, metalness: 0 });

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/tire/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 1.55]} scale={0.515}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.polySurface9_RUBBER_TIRE_0.geometry} material={rubber} />
          <mesh geometry={nodes.polySurface9_RUBBER_TIRE_0_1.geometry} material={rubber} />
          <mesh geometry={nodes.polySurface9_RUBBER_DUST_0.geometry} material={rubber} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tire/scene.gltf')
