/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/wheel/scene.gltf -t -r public
Author: Serjogasan (https://sketchfab.com/Serjogasan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wheel-44223c0adba8449b8438ede3441b256d
Title: Wheel
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Wheel06LowPoly_Wheel06_0: THREE.Mesh
  }
  materials: {
    ['Wheel.06']: THREE.MeshStandardMaterial
  }
}

export default function Wheel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/wheel/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.029}>
      <mesh geometry={nodes.Wheel06LowPoly_Wheel06_0.geometry} material={materials['Wheel.06']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/wheel/scene.gltf')
