/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/car/scene.gltf -t -r public
Author: COOL601 (https://sketchfab.com/COOL601)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-mp4-12c-ultimate-80f19f7f5aac428985356987769538fe
Title: Mclaren MP4-12C Ultimate
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { MeshPhysicalMaterial } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_62: THREE.Mesh
    Object_65: THREE.Mesh
    Object_66: THREE.Mesh
    Object_67: THREE.Mesh
    Object_68: THREE.Mesh
    Object_69: THREE.Mesh
    Object_70: THREE.Mesh
    Object_71: THREE.Mesh
    Object_72: THREE.Mesh
    Object_73: THREE.Mesh
    Object_76: THREE.Mesh
    Object_77: THREE.Mesh
    Object_78: THREE.Mesh
    Object_79: THREE.Mesh
    Object_80: THREE.Mesh
    Object_81: THREE.Mesh
    Object_82: THREE.Mesh
    Object_83: THREE.Mesh
    Object_84: THREE.Mesh
    Object_87: THREE.Mesh
    Object_88: THREE.Mesh
    Object_89: THREE.Mesh
    Object_90: THREE.Mesh
    Object_91: THREE.Mesh
    Object_92: THREE.Mesh
    Object_93: THREE.Mesh
    Object_94: THREE.Mesh
    Object_95: THREE.Mesh
    Object_98: THREE.Mesh
    Object_99: THREE.Mesh
    Object_100: THREE.Mesh
    Object_101: THREE.Mesh
    Object_102: THREE.Mesh
    Object_105: THREE.Mesh
    Object_106: THREE.Mesh
    Object_107: THREE.Mesh
    Object_108: THREE.Mesh
    Object_109: THREE.Mesh
    Object_112: THREE.Mesh
    Object_113: THREE.Mesh
    Object_114: THREE.Mesh
    Object_115: THREE.Mesh
    Object_116: THREE.Mesh
    Object_117: THREE.Mesh
    Object_120: THREE.Mesh
    Object_121: THREE.Mesh
    Object_122: THREE.Mesh
    Object_123: THREE.Mesh
    Object_124: THREE.Mesh
    Object_125: THREE.Mesh
  }
  materials: {
    ['Paint.001']: THREE.MeshStandardMaterial
    ['Matte__FF000000_.001']: THREE.MeshStandardMaterial
    koplamp_binnen: THREE.MeshStandardMaterial
    ['cockpit__spec_.001']: THREE.MeshStandardMaterial
    ['Matte__FF999999_.001']: THREE.MeshStandardMaterial
    ['leather__spec_.001']: THREE.MeshStandardMaterial
    stitches: THREE.MeshStandardMaterial
    ['mesh2__spec_.001']: THREE.MeshStandardMaterial
    spiegels: THREE.MeshPhysicalMaterial
    Glass: THREE.MeshStandardMaterial
    ['badges__spec_.001']: THREE.MeshStandardMaterial
    ['carbonint__spec_.001']: THREE.MeshStandardMaterial
    ['misc__spec_.001']: THREE.MeshStandardMaterial
    ['vehiclelights128.001']: THREE.MeshStandardMaterial
    ['vehiclelights1.001']: THREE.MeshStandardMaterial
    ['vehiclelights2.001']: THREE.MeshStandardMaterial
    ['vehiclelights3.001']: THREE.MeshStandardMaterial
    binnen_koplamp: THREE.MeshStandardMaterial
    ['steeringwheel__s.001']: THREE.MeshStandardMaterial
    ['water__spec_.001']: THREE.MeshStandardMaterial
    ['bumper_frame__sp.001']: THREE.MeshStandardMaterial
    ['Matte__FF00001.001']: THREE.MeshStandardMaterial
    ['Matte__FF00002.001']: THREE.MeshStandardMaterial
    ['Matte__BA000000_.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['guages__spec_.001']: THREE.MeshStandardMaterial
    ['carpet__spec_.001']: THREE.MeshStandardMaterial
    ['mclarenint__spec.001']: THREE.MeshStandardMaterial
    ANgle_eye_inside: THREE.MeshStandardMaterial
    angle_eyes: THREE.MeshStandardMaterial
    Carbon: THREE.MeshStandardMaterial
    ['Carbon.001']: THREE.MeshStandardMaterial
    ['Material.069']: THREE.MeshStandardMaterial
    ['Material.070']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    Exhaust: THREE.MeshStandardMaterial
    Exhaust_inside: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.074']: THREE.MeshStandardMaterial
    mclaren_logo: THREE.MeshStandardMaterial
    ['Silver_METAL.004']: THREE.MeshStandardMaterial
    ['Tires2.004']: THREE.MeshStandardMaterial
    ['SCUDO_Yellow.004']: THREE.MeshStandardMaterial
    ['Red_METAL.004']: THREE.MeshStandardMaterial
    ['BRAKES_4K.004']: THREE.MeshStandardMaterial
    ['Black_Metal.004']: THREE.MeshStandardMaterial
    ['Black_METAL1.004']: THREE.MeshStandardMaterial
    ['koplamp_binnen.006']: THREE.MeshStandardMaterial
    ['mclaren_logo.003']: THREE.MeshStandardMaterial
    ['Silver_METAL.003']: THREE.MeshStandardMaterial
    ['Tires2.003']: THREE.MeshStandardMaterial
    ['SCUDO_Yellow.003']: THREE.MeshStandardMaterial
    ['Red_METAL.003']: THREE.MeshStandardMaterial
    ['BRAKES_4K.003']: THREE.MeshStandardMaterial
    ['Black_Metal.003']: THREE.MeshStandardMaterial
    ['Black_METAL1.003']: THREE.MeshStandardMaterial
    ['koplamp_binnen.004']: THREE.MeshStandardMaterial
    ['mclaren_logo.002']: THREE.MeshStandardMaterial
    ['Silver_METAL.005']: THREE.MeshStandardMaterial
    ['Tires2.005']: THREE.MeshStandardMaterial
    ['SCUDO_Yellow.005']: THREE.MeshStandardMaterial
    ['Red_METAL.005']: THREE.MeshStandardMaterial
    ['BRAKES_4K.005']: THREE.MeshStandardMaterial
    ['Black_Metal.005']: THREE.MeshStandardMaterial
    ['Black_METAL1.005']: THREE.MeshStandardMaterial
    ['koplamp_binnen.008']: THREE.MeshStandardMaterial
    ['mclaren_logo.004']: THREE.MeshStandardMaterial
    ['Silver_METAL.002']: THREE.MeshStandardMaterial
    ['Tires2.002']: THREE.MeshStandardMaterial
    ['SCUDO_Yellow.002']: THREE.MeshStandardMaterial
    ['Red_METAL.002']: THREE.MeshStandardMaterial
    ['BRAKES_4K.002']: THREE.MeshStandardMaterial
    ['Black_Metal.002']: THREE.MeshStandardMaterial
    ['Black_METAL1.002']: THREE.MeshStandardMaterial
    ['koplamp_binnen.002']: THREE.MeshStandardMaterial
    ['mclaren_logo.001']: THREE.MeshStandardMaterial
    ['Brake_Pad.004']: THREE.MeshStandardMaterial
    ['Brake_Disc_1.004']: THREE.MeshStandardMaterial
    ['Black_METAL.004']: THREE.MeshStandardMaterial
    ['Black_MATTE.004']: THREE.MeshStandardMaterial
    ['Brake_Pad.003']: THREE.MeshStandardMaterial
    ['Brake_Disc_1.003']: THREE.MeshStandardMaterial
    ['Black_METAL.003']: THREE.MeshStandardMaterial
    ['Black_MATTE.003']: THREE.MeshStandardMaterial
    ['Brake_Pad.005']: THREE.MeshStandardMaterial
    ['Brake_Disc_1.005']: THREE.MeshStandardMaterial
    ['Black_METAL.005']: THREE.MeshStandardMaterial
    ['Black_MATTE.005']: THREE.MeshStandardMaterial
    ['mini_brake.001']: THREE.MeshStandardMaterial
    ['Brake_Pad.002']: THREE.MeshStandardMaterial
    ['Brake_Disc_1.002']: THREE.MeshStandardMaterial
    ['Black_METAL.002']: THREE.MeshStandardMaterial
    ['Black_MATTE.002']: THREE.MeshStandardMaterial
    mini_brake: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/maclaren/scene.gltf') as GLTFResult;
  const newMaterial = new MeshPhysicalMaterial({ color: 'grey', roughness: 0, metalness: 0.5 });
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.65}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.07, -0.09, 2.56]}>
            <group position={[0, 0.41, -2.75]} rotation={[-1.57, 0, 0]}>
              <group position={[0, -0.03, -0.41]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_6.geometry} material={newMaterial} />
                {/* <mesh geometry={nodes.Object_6.geometry} material={materials['Paint.001']} /> */}
                <mesh geometry={nodes.Object_7.geometry} material={materials['Matte__FF000000_.001']} />
                <mesh geometry={nodes.Object_8.geometry} material={materials.koplamp_binnen} />
                <mesh geometry={nodes.Object_9.geometry} material={materials['cockpit__spec_.001']} />
                <mesh geometry={nodes.Object_10.geometry} material={materials['Matte__FF999999_.001']} />
                <mesh geometry={nodes.Object_11.geometry} material={materials['leather__spec_.001']} />
                <mesh geometry={nodes.Object_12.geometry} material={materials.stitches} />
                <mesh geometry={nodes.Object_13.geometry} material={materials['mesh2__spec_.001']} />
                <mesh geometry={nodes.Object_14.geometry} material={materials.spiegels} />
                <mesh geometry={nodes.Object_15.geometry} material={materials.Glass} />
                <mesh geometry={nodes.Object_16.geometry} material={materials['badges__spec_.001']} />
                <mesh geometry={nodes.Object_17.geometry} material={materials['carbonint__spec_.001']} />
                <mesh geometry={nodes.Object_18.geometry} material={materials['misc__spec_.001']} />
                <mesh geometry={nodes.Object_19.geometry} material={materials['vehiclelights128.001']} />
                <mesh geometry={nodes.Object_20.geometry} material={materials['vehiclelights1.001']} />
                <mesh geometry={nodes.Object_21.geometry} material={materials['vehiclelights2.001']} />
                <mesh geometry={nodes.Object_22.geometry} material={materials['vehiclelights3.001']} />
                <mesh geometry={nodes.Object_23.geometry} material={materials.binnen_koplamp} />
                <mesh geometry={nodes.Object_24.geometry} material={materials['steeringwheel__s.001']} />
                <mesh geometry={nodes.Object_25.geometry} material={materials['water__spec_.001']} />
                <mesh geometry={nodes.Object_26.geometry} material={materials['bumper_frame__sp.001']} />
                <mesh geometry={nodes.Object_27.geometry} material={materials['Matte__FF00001.001']} />
                <mesh geometry={nodes.Object_28.geometry} material={materials['Matte__FF00002.001']} />
                <mesh geometry={nodes.Object_29.geometry} material={materials['Matte__BA000000_.001']} />
                <mesh geometry={nodes.Object_30.geometry} material={materials['Material.003']} />
                <mesh geometry={nodes.Object_31.geometry} material={materials['guages__spec_.001']} />
                <mesh geometry={nodes.Object_32.geometry} material={materials['carpet__spec_.001']} />
                <mesh geometry={nodes.Object_33.geometry} material={materials['mclarenint__spec.001']} />
                <mesh geometry={nodes.Object_34.geometry} material={materials.ANgle_eye_inside} />
                <mesh geometry={nodes.Object_35.geometry} material={materials.angle_eyes} />
                <mesh geometry={nodes.Object_36.geometry} material={materials.Carbon} />
                <mesh geometry={nodes.Object_37.geometry} material={materials['Carbon.001']} />
                <mesh geometry={nodes.Object_38.geometry} material={materials['Material.069']} />
                <mesh geometry={nodes.Object_39.geometry} material={materials['Material.070']} />
                <mesh geometry={nodes.Object_40.geometry} material={materials['Material.008']} />
                <mesh geometry={nodes.Object_41.geometry} material={materials['Material.009']} />
                <mesh geometry={nodes.Object_42.geometry} material={materials['Material.036']} />
                <mesh geometry={nodes.Object_43.geometry} material={materials['Material.004']} />
                <mesh geometry={nodes.Object_44.geometry} material={materials['Material.005']} />
                <mesh geometry={nodes.Object_45.geometry} material={materials['Material.016']} />
                <mesh geometry={nodes.Object_46.geometry} material={materials['Material.017']} />
                <mesh geometry={nodes.Object_47.geometry} material={materials.Exhaust} />
                <mesh geometry={nodes.Object_48.geometry} material={materials.Exhaust_inside} />
                <mesh geometry={nodes.Object_49.geometry} material={materials['Material.010']} />
                <mesh geometry={nodes.Object_50.geometry} material={materials['Material.074']} />
                <mesh geometry={nodes.Object_51.geometry} material={materials.mclaren_logo} />
              </group>
            </group>
            <group position={[1.38, 0.53, -0.61]} rotation={[-1.57, 0, 0]}>
              <group position={[-1.38, 2.1, -0.53]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_54.geometry} material={materials['Silver_METAL.004']} />
                <mesh geometry={nodes.Object_55.geometry} material={materials['Tires2.004']} />
                <mesh geometry={nodes.Object_56.geometry} material={materials['SCUDO_Yellow.004']} />
                <mesh geometry={nodes.Object_57.geometry} material={materials['Red_METAL.004']} />
                <mesh geometry={nodes.Object_58.geometry} material={materials['BRAKES_4K.004']} />
                <mesh geometry={nodes.Object_59.geometry} material={materials['Black_Metal.004']} />
                <mesh geometry={nodes.Object_60.geometry} material={materials['Black_METAL1.004']} />
                <mesh geometry={nodes.Object_61.geometry} material={materials['koplamp_binnen.006']} />
                <mesh geometry={nodes.Object_62.geometry} material={materials['mclaren_logo.003']} />
              </group>
            </group>
            <group position={[-1.4, 0.53, -0.62]} rotation={[-1.57, 0, 0]}>
              <group position={[1.4, 2.1, -0.53]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_65.geometry} material={materials['Silver_METAL.003']} />
                <mesh geometry={nodes.Object_66.geometry} material={materials['Tires2.003']} />
                <mesh geometry={nodes.Object_67.geometry} material={materials['SCUDO_Yellow.003']} />
                <mesh geometry={nodes.Object_68.geometry} material={materials['Red_METAL.003']} />
                <mesh geometry={nodes.Object_69.geometry} material={materials['BRAKES_4K.003']} />
                <mesh geometry={nodes.Object_70.geometry} material={materials['Black_Metal.003']} />
                <mesh geometry={nodes.Object_71.geometry} material={materials['Black_METAL1.003']} />
                <mesh geometry={nodes.Object_72.geometry} material={materials['koplamp_binnen.004']} />
                <mesh geometry={nodes.Object_73.geometry} material={materials['mclaren_logo.002']} />
              </group>
            </group>
            <group position={[1.4, 0.53, -4.88]} rotation={[-1.57, 0, 0]}>
              <group position={[-1.4, -2.17, -0.53]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_76.geometry} material={materials['Silver_METAL.005']} />
                <mesh geometry={nodes.Object_77.geometry} material={materials['Tires2.005']} />
                <mesh geometry={nodes.Object_78.geometry} material={materials['SCUDO_Yellow.005']} />
                <mesh geometry={nodes.Object_79.geometry} material={materials['Red_METAL.005']} />
                <mesh geometry={nodes.Object_80.geometry} material={materials['BRAKES_4K.005']} />
                <mesh geometry={nodes.Object_81.geometry} material={materials['Black_Metal.005']} />
                <mesh geometry={nodes.Object_82.geometry} material={materials['Black_METAL1.005']} />
                <mesh geometry={nodes.Object_83.geometry} material={materials['koplamp_binnen.008']} />
                <mesh geometry={nodes.Object_84.geometry} material={materials['mclaren_logo.004']} />
              </group>
            </group>
            <group position={[-1.38, 0.53, -4.89]} rotation={[-1.57, 0, 0]}>
              <group position={[1.38, -2.17, -0.53]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_87.geometry} material={materials['Silver_METAL.002']} />
                <mesh geometry={nodes.Object_88.geometry} material={materials['Tires2.002']} />
                <mesh geometry={nodes.Object_89.geometry} material={materials['SCUDO_Yellow.002']} />
                <mesh geometry={nodes.Object_90.geometry} material={materials['Red_METAL.002']} />
                <mesh geometry={nodes.Object_91.geometry} material={materials['BRAKES_4K.002']} />
                <mesh geometry={nodes.Object_92.geometry} material={materials['Black_Metal.002']} />
                <mesh geometry={nodes.Object_93.geometry} material={materials['Black_METAL1.002']} />
                <mesh geometry={nodes.Object_94.geometry} material={materials['koplamp_binnen.002']} />
                <mesh geometry={nodes.Object_95.geometry} material={materials['mclaren_logo.001']} />
              </group>
            </group>
            <group position={[1.32, 0.53, -0.78]} rotation={[-1.57, 0, 0]}>
              <group position={[-1.32, 1.93, -0.53]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_98.geometry} material={materials['Brake_Pad.004']} />
                <mesh geometry={nodes.Object_99.geometry} material={materials['Silver_METAL.004']} />
                <mesh geometry={nodes.Object_100.geometry} material={materials['Brake_Disc_1.004']} />
                <mesh geometry={nodes.Object_101.geometry} material={materials['Black_METAL.004']} />
                <mesh geometry={nodes.Object_102.geometry} material={materials['Black_MATTE.004']} />
              </group>
            </group>
            <group position={[-1.34, 0.53, -0.79]} rotation={[-1.57, 0, 0]}>
              <group position={[1.34, 1.92, -0.53]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_105.geometry} material={materials['Brake_Pad.003']} />
                <mesh geometry={nodes.Object_106.geometry} material={materials['Silver_METAL.003']} />
                <mesh geometry={nodes.Object_107.geometry} material={materials['Brake_Disc_1.003']} />
                <mesh geometry={nodes.Object_108.geometry} material={materials['Black_METAL.003']} />
                <mesh geometry={nodes.Object_109.geometry} material={materials['Black_MATTE.003']} />
              </group>
            </group>
            <group position={[1.35, 0.53, -4.71]} rotation={[-1.57, 0, 0]}>
              <group position={[-1.35, -2, -0.53]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_112.geometry} material={materials['Brake_Pad.005']} />
                <mesh geometry={nodes.Object_113.geometry} material={materials['Silver_METAL.005']} />
                <mesh geometry={nodes.Object_114.geometry} material={materials['Brake_Disc_1.005']} />
                <mesh geometry={nodes.Object_115.geometry} material={materials['Black_METAL.005']} />
                <mesh geometry={nodes.Object_116.geometry} material={materials['Black_MATTE.005']} />
                <mesh geometry={nodes.Object_117.geometry} material={materials['mini_brake.001']} />
              </group>
            </group>
            <group position={[-1.33, 0.53, -4.72]} rotation={[-1.57, 0, 0]}>
              <group position={[1.32, -2, -0.53]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Object_120.geometry} material={materials['Brake_Pad.002']} />
                <mesh geometry={nodes.Object_121.geometry} material={materials['Silver_METAL.002']} />
                <mesh geometry={nodes.Object_122.geometry} material={materials['Brake_Disc_1.002']} />
                <mesh geometry={nodes.Object_123.geometry} material={materials['Black_METAL.002']} />
                <mesh geometry={nodes.Object_124.geometry} material={materials['Black_MATTE.002']} />
                <mesh geometry={nodes.Object_125.geometry} material={materials.mini_brake} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/maclaren/scene.gltf')
