/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/wheel2/scene.gltf -t -r public
Author: Serjogasan (https://sketchfab.com/Serjogasan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-car-wheel-e0fd5582e2bc402594bc8e40f5c68609
Title: Free Car Wheel
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Wheel04LowPoly_Wheel04_0: THREE.Mesh
  }
  materials: {
    ['Wheel.04']: THREE.MeshStandardMaterial
  }
}

export default function Wheel2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/wheel2/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.029}>
      <mesh geometry={nodes.Wheel04LowPoly_Wheel04_0.geometry} material={materials['Wheel.04']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/wheel2/scene.gltf')
